<?php
/**
 * Chức năng: VaccineSeeder nạp duy nhất đúng 40 vắc xin thật từ PDF chính thức của Medicare Cờ Đỏ.
 * Lý do chỉnh sửa: Loại bỏ toàn bộ các gói vắc xin mẫu tự tạo, chỉ giữ đúng 40 vắc xin thật.
 */

namespace Modules\VaccineRegistration\Database\Seeders;

use Database\Seeders\Concerns\PreventsProductionSeeding;
use Illuminate\Database\Seeder;
use Modules\VaccineRegistration\Models\Vaccine;

class VaccineSeeder extends Seeder
{
    use PreventsProductionSeeding;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->assertSafeSeedingTarget();

        $vaccines = [
            // --- ĐÚNG 40 VẮC XIN LẺ THẬT TỪ PDF MEDICARE CỜ ĐỎ ---
            [
                'name' => 'Hexaxim',
                'price' => 1050000,
                'sale_price' => 1050000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'Sanofi Pasteur',
                'dosage' => '0.5ml',
                'category' => 'Vắc xin 6 trong 1',
                'is_featured' => true,
                'sort_order' => 1,
                'description' => 'Vắc xin 6in1 phòng 6 bệnh truyền nhiễm nguy hiểm: Bạch hầu – Ho gà – Uốn ván – Bại liệt – Viêm gan B – Hib.',
                'disease_prevention' => 'Bạch hầu, Ho gà, Uốn ván, Bại liệt, Viêm gan B, Hib',
                'age_group' => 'Trẻ em (6 tuần – 24 tháng)',
                'origin' => 'Pháp',
                'image' => '1-hexaxim.jpg',
            ],
            [
                'name' => 'Infanrix Hexa',
                'price' => 1050000,
                'sale_price' => 1050000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Vắc xin 6 trong 1',
                'is_featured' => true,
                'sort_order' => 2,
                'description' => 'Vắc xin 6in1 kết hợp phòng Bạch hầu, Ho gà, Uốn ván, Bại liệt, Viêm gan B và các bệnh do vi khuẩn Hib.',
                'disease_prevention' => 'Bạch hầu, Ho gà, Uốn ván, Bại liệt, Viêm gan B, Hib',
                'age_group' => 'Trẻ em (6 tuần – 24 tháng)',
                'origin' => 'Bỉ',
                'image' => '2-infanrix-hexa.jfif',
            ],
            [
                'name' => 'Rotarix',
                'price' => 900000,
                'sale_price' => 900000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '1.5ml',
                'category' => 'Tiêu chảy Rota',
                'is_featured' => true,
                'sort_order' => 3,
                'description' => 'Vắc xin đường uống phòng bệnh tiêu chảy cấp do Rotavirus gây ra ở trẻ nhỏ.',
                'disease_prevention' => 'Tiêu chảy cấp do Rotavirus',
                'age_group' => 'Trẻ em (6 tuần – 24 tuần)',
                'origin' => 'Bỉ',
                'image' => '3-rotarix.jpg',
            ],
            [
                'name' => 'Rotavin',
                'price' => 490000,
                'sale_price' => 490000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'POLYVAC',
                'dosage' => '2ml',
                'category' => 'Tiêu chảy Rota',
                'is_featured' => false,
                'sort_order' => 4,
                'description' => 'Vắc xin uồng phòng tiêu chảy do Rotavirus sản xuất tại Việt Nam.',
                'disease_prevention' => 'Tiêu chảy cấp do Rotavirus',
                'age_group' => 'Trẻ em (6 tuần – 24 tuần)',
                'origin' => 'Việt Nam',
                'image' => '4-rotavin.jpg',
            ],
            [
                'name' => 'BCG',
                'price' => 125000,
                'sale_price' => 125000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'IVAC',
                'dosage' => '0.1ml',
                'category' => 'Lao',
                'is_featured' => false,
                'sort_order' => 5,
                'description' => 'Vắc xin phòng bệnh lao cho trẻ sơ sinh càng sớm càng tốt sau khi sinh.',
                'disease_prevention' => 'Bệnh Lao',
                'age_group' => 'Trẻ em sơ sinh (<1 tháng)',
                'origin' => 'Việt Nam',
                'image' => '5-bcg.jpg',
            ],
            [
                'name' => 'Jeev 3mcg',
                'price' => 360000,
                'sale_price' => 360000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Biological E. Limited',
                'dosage' => '0.5ml',
                'category' => 'Viêm não Nhật Bản',
                'is_featured' => false,
                'sort_order' => 6,
                'description' => 'Vắc xin phòng bệnh Viêm não Nhật Bản cho trẻ em.',
                'disease_prevention' => 'Viêm não Nhật Bản',
                'age_group' => 'Trẻ em 1-3 tuổi',
                'origin' => 'Ấn Độ',
                'image' => '6-jeev-3mcg.png',
            ],
            [
                'name' => 'Jeev 6mcg',
                'price' => 470000,
                'sale_price' => 470000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Biological E. Limited',
                'dosage' => '0.5ml',
                'category' => 'Viêm não Nhật Bản',
                'is_featured' => false,
                'sort_order' => 7,
                'description' => 'Vắc xin phòng bệnh Viêm não Nhật Bản cho trẻ từ 3 tuổi trở lên và người lớn.',
                'disease_prevention' => 'Viêm não Nhật Bản',
                'age_group' => '3 tuổi đến 49 tuổi',
                'origin' => 'Ấn Độ',
                'image' => '7-jeev-6mcg.webp',
            ],
            [
                'name' => 'Jevax',
                'price' => 170000,
                'sale_price' => 170000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'VABIOTECH',
                'dosage' => '0.5ml',
                'category' => 'Viêm não Nhật Bản',
                'is_featured' => false,
                'sort_order' => 8,
                'description' => 'Vắc xin phòng bệnh Viêm não Nhật Bản bất hoạt.',
                'disease_prevention' => 'Viêm não Nhật Bản',
                'age_group' => '1 tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '8-jevax.jpg',
            ],
            [
                'name' => 'Imojev',
                'price' => 920000,
                'sale_price' => 920000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'Sanofi Pasteur',
                'dosage' => '0.5ml',
                'category' => 'Viêm não Nhật Bản',
                'is_featured' => true,
                'sort_order' => 9,
                'description' => 'Vắc xin thế hệ mới phòng bệnh Viêm não Nhật Bản sống giảm độc lực.',
                'disease_prevention' => 'Viêm não Nhật Bản',
                'age_group' => '9 tháng tuổi trở lên',
                'origin' => 'Thái Lan',
                'image' => '9-imojev.jpg',
            ],
            [
                'name' => 'Prevenar 13',
                'price' => 1490000,
                'sale_price' => 1490000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'Pfizer',
                'dosage' => '0.5ml',
                'category' => 'Phế cầu',
                'is_featured' => true,
                'sort_order' => 10,
                'description' => 'Vắc xin phòng các bệnh xâm lấn do phế cầu khuẩn gây ra: Viêm phổi, viêm màng não, nhiễm trùng huyết.',
                'disease_prevention' => 'Phế cầu 13 (Viêm phổi, viêm màng não)',
                'age_group' => '6 tuần tuổi trở lên',
                'origin' => 'Bỉ',
                'image' => '10-prevenar-13.jpg',
            ],
            [
                'name' => 'Prevenar 20',
                'price' => 1750000,
                'sale_price' => 1750000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'Pfizer',
                'dosage' => '0.5ml',
                'category' => 'Phế cầu',
                'is_featured' => true,
                'sort_order' => 11,
                'description' => 'Vắc xin phế cầu 20 thế hệ mới bảo vệ diện rộng phòng 20 serotype phế cầu khuẩn.',
                'disease_prevention' => 'Phế cầu 20 (Bảo vệ diện rộng)',
                'age_group' => '6 tuần tuổi trở lên',
                'origin' => 'Bỉ',
                'image' => '11-prevenar-20.jfif',
            ],
            [
                'name' => 'Influvac Tetra',
                'price' => 350000,
                'sale_price' => 350000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'Abbott',
                'dosage' => '0.5ml',
                'category' => 'Cúm mùa',
                'is_featured' => true,
                'sort_order' => 12,
                'description' => 'Vắc xin cúm tứ giá phòng 4 chủng virus cúm mùa phổ biến.',
                'disease_prevention' => 'Cúm mùa tứ giá',
                'age_group' => '6 tháng tuổi trở lên',
                'origin' => 'Hà Lan',
                'image' => '12-influvac-tetra.jpg',
            ],
            [
                'name' => 'Vaxigrip Tetra',
                'price' => 350000,
                'sale_price' => 350000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'Sanofi Pasteur',
                'dosage' => '0.5ml',
                'category' => 'Cúm mùa',
                'is_featured' => true,
                'sort_order' => 13,
                'description' => 'Vắc xin cúm tứ giá phòng ngừa biến chứng viêm phổi do virus cúm mùa.',
                'disease_prevention' => 'Cúm mùa tứ giá',
                'age_group' => '6 tháng tuổi trở lên',
                'origin' => 'Pháp',
                'image' => '13-vaxigrip-tetra.jpg',
            ],
            [
                'name' => 'IVACFLU-S',
                'price' => 250000,
                'sale_price' => 250000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'IVAC',
                'dosage' => '0.5ml',
                'category' => 'Cúm mùa',
                'is_featured' => false,
                'sort_order' => 14,
                'description' => 'Vắc xin phòng bệnh cúm mùa sản xuất tại Việt Nam.',
                'disease_prevention' => 'Cúm mùa',
                'age_group' => '6 tháng tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '14-ivacflu-s.jpg',
            ],
            [
                'name' => 'GC Flus',
                'price' => 350000,
                'sale_price' => 350000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'GC Pharma',
                'dosage' => '0.5ml',
                'category' => 'Cúm mùa',
                'is_featured' => false,
                'sort_order' => 15,
                'description' => 'Vắc xin phòng bệnh cúm mùa tứ giá của Hàn Quốc.',
                'disease_prevention' => 'Cúm mùa',
                'age_group' => '6 tháng tuổi trở lên',
                'origin' => 'Hàn Quốc',
                'image' => '15-gc-flus.jpg',
            ],
            [
                'name' => 'Mengoc BC',
                'price' => 310000,
                'sale_price' => 310000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Finlay Institute',
                'dosage' => '0.5ml',
                'category' => 'Mô cầu BC',
                'is_featured' => false,
                'sort_order' => 16,
                'description' => 'Vắc xin phòng bệnh viêm màng não do vi khuẩn Meningococcus tuýp B và C.',
                'disease_prevention' => 'Viêm màng não mô cầu BC',
                'age_group' => '6 tháng đến 45 tuổi',
                'origin' => 'Cuba',
                'image' => '16-mengoc-bc.jpg',
            ],
            [
                'name' => 'Bexsero',
                'price' => 1850000,
                'sale_price' => 1850000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Mô cầu B',
                'is_featured' => true,
                'sort_order' => 17,
                'description' => 'Vắc xin phòng bệnh viêm màng não do vi khuẩn mô cầu tuýp B thế hệ mới.',
                'disease_prevention' => 'Viêm màng não mô cầu B',
                'age_group' => '2 tháng đến 50 tuổi',
                'origin' => 'Ý',
                'image' => '17-bexsero.jpg',
            ],
            [
                'name' => 'Nimerix',
                'price' => 1750000,
                'sale_price' => 1750000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Mô cầu ACYW',
                'is_featured' => true,
                'sort_order' => 18,
                'description' => 'Vắc xin phòng bệnh viêm màng não do 4 tuýp vi khuẩn mô cầu A, C, Y, W-135.',
                'disease_prevention' => 'Viêm màng não mô cầu A, C, Y, W',
                'age_group' => '2 tháng trở lên',
                'origin' => 'Bỉ',
                'image' => '18-nimerix.jpg',
            ],
            [
                'name' => 'MMR',
                'price' => 250000,
                'sale_price' => 250000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Serum Institute',
                'dosage' => '0.5ml',
                'category' => 'Sởi - Quai bị - Rubella',
                'is_featured' => false,
                'sort_order' => 19,
                'description' => 'Vắc xin 3in1 kết hợp phòng Sởi – Quai bị – Rubella.',
                'disease_prevention' => 'Sởi, Quai bị, Rubella',
                'age_group' => '12 tháng – 10 tuổi',
                'origin' => 'Ấn Độ',
                'image' => '19-mmr.jpg',
            ],
            [
                'name' => 'Priorix',
                'price' => 485000,
                'sale_price' => 485000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Sởi - Quai bị - Rubella',
                'is_featured' => false,
                'sort_order' => 20,
                'description' => 'Vắc xin 3in1 Sởi – Quai bị – Rubella của Bỉ.',
                'disease_prevention' => 'Sởi, Quai bị, Rubella',
                'age_group' => '9 tháng – người lớn',
                'origin' => 'Bỉ',
                'image' => '20-priorix.png',
            ],
            [
                'name' => 'MMR II',
                'price' => 480000,
                'sale_price' => 480000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'MSD',
                'dosage' => '0.5ml',
                'category' => 'Sởi - Quai bị - Rubella',
                'is_featured' => true,
                'sort_order' => 21,
                'description' => 'Vắc xin 3in1 phòng Sởi – Quai bị – Rubella nổi tiếng của Mỹ.',
                'disease_prevention' => 'Sởi, Quai bị, Rubella',
                'age_group' => '12 tháng – người lớn',
                'origin' => 'Mỹ',
                'image' => '21-mmr-ii.png',
            ],
            [
                'name' => 'Barycela',
                'price' => 865000,
                'sale_price' => 865000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GC Pharma',
                'dosage' => '0.5ml',
                'category' => 'Thủy đậu',
                'is_featured' => false,
                'sort_order' => 22,
                'description' => 'Vắc xin phòng bệnh Thủy đậu của Hàn Quốc.',
                'disease_prevention' => 'Thủy đậu',
                'age_group' => '12 tháng – 12 tuổi',
                'origin' => 'Hàn Quốc',
                'image' => '22-barycela.webp',
            ],
            [
                'name' => 'Varilrix',
                'price' => 1045000,
                'sale_price' => 1045000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Thủy đậu',
                'is_featured' => true,
                'sort_order' => 23,
                'description' => 'Vắc xin phòng bệnh Thủy đậu phòng ngừa sẹo và biến chứng viêm phổi do thủy đậu.',
                'disease_prevention' => 'Thủy đậu',
                'age_group' => '9 tháng tuổi trở lên',
                'origin' => 'Bỉ',
                'image' => '23-varilrix.jpg',
            ],
            [
                'name' => 'Varivax',
                'price' => 1250000,
                'sale_price' => 1250000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'MSD',
                'dosage' => '0.5ml',
                'category' => 'Thủy đậu',
                'is_featured' => false,
                'sort_order' => 24,
                'description' => 'Vắc xin phòng bệnh Thủy đậu của Mỹ.',
                'disease_prevention' => 'Thủy đậu',
                'age_group' => '12 tháng tuổi trở lên',
                'origin' => 'Mỹ',
                'image' => '24-varivax.jpg',
            ],
            [
                'name' => 'Twinrix',
                'price' => 650000,
                'sale_price' => 650000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '1ml',
                'category' => 'Viêm gan A-B',
                'is_featured' => true,
                'sort_order' => 25,
                'description' => 'Vắc xin kết hợp phòng cả 2 bệnh Viêm gan A và Viêm gan B.',
                'disease_prevention' => 'Viêm gan A – B',
                'age_group' => '12 tháng trở lên',
                'origin' => 'Bỉ',
                'image' => '25-twinrix.jfif',
            ],
            [
                'name' => 'Havax',
                'price' => 235000,
                'sale_price' => 235000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'VABIOTECH',
                'dosage' => '0.5ml',
                'category' => 'Viêm gan A',
                'is_featured' => false,
                'sort_order' => 26,
                'description' => 'Vắc xin phòng bệnh Viêm gan A sản xuất tại Việt Nam.',
                'disease_prevention' => 'Viêm gan A',
                'age_group' => '2 tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '26-havax.png',
            ],
            [
                'name' => 'Avaxim 80U',
                'price' => 600000,
                'sale_price' => 600000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Sanofi Pasteur',
                'dosage' => '0.5ml',
                'category' => 'Viêm gan A',
                'is_featured' => false,
                'sort_order' => 27,
                'description' => 'Vắc xin phòng bệnh Viêm gan A của Pháp.',
                'disease_prevention' => 'Viêm gan A',
                'age_group' => '12 tháng đến 15 tuổi',
                'origin' => 'Pháp',
                'image' => '27-avaxim-80u.jpg',
            ],
            [
                'name' => 'Gene-Hbvax 0,5ml',
                'price' => 200000,
                'sale_price' => 200000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'VABIOTECH',
                'dosage' => '0.5ml',
                'category' => 'Viêm gan B',
                'is_featured' => false,
                'sort_order' => 28,
                'description' => 'Vắc xin phòng Viêm gan B tái tổ hợp cho trẻ em.',
                'disease_prevention' => 'Viêm gan B',
                'age_group' => 'Trẻ em (Sơ sinh – 10 tuổi)',
                'origin' => 'Việt Nam',
                'image' => '28-gene-hbvax-0-5ml.jpg',
            ],
            [
                'name' => 'Gene-Hbvax 1ml',
                'price' => 250000,
                'sale_price' => 250000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'VABIOTECH',
                'dosage' => '1ml',
                'category' => 'Viêm gan B',
                'is_featured' => false,
                'sort_order' => 29,
                'description' => 'Vắc xin phòng Viêm gan B tái tổ hợp cho người lớn.',
                'disease_prevention' => 'Viêm gan B',
                'age_group' => '10 tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '29-gene-hbvax-1ml.jpg',
            ],
            [
                'name' => 'Heberbiovac 0,5 ml',
                'price' => 200000,
                'sale_price' => 200000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'CIGB',
                'dosage' => '0.5ml',
                'category' => 'Viêm gan B',
                'is_featured' => false,
                'sort_order' => 30,
                'description' => 'Vắc xin phòng Viêm gan B của Cuba cho trẻ em.',
                'disease_prevention' => 'Viêm gan B',
                'age_group' => 'Trẻ em (Sơ sinh – 10 tuổi)',
                'origin' => 'Cuba',
                'image' => '30-heberbiovac-0-5ml.jpg',
            ],
            [
                'name' => 'Heberbiovac 1 ml',
                'price' => 250000,
                'sale_price' => 250000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'CIGB',
                'dosage' => '1ml',
                'category' => 'Viêm gan B',
                'is_featured' => false,
                'sort_order' => 31,
                'description' => 'Vắc xin phòng Viêm gan B của Cuba cho người lớn.',
                'disease_prevention' => 'Viêm gan B',
                'age_group' => '10 tuổi trở lên',
                'origin' => 'Cuba',
                'image' => '31-heberbiovac-1ml.webp',
            ],
            [
                'name' => 'mORcvax',
                'price' => 115000,
                'sale_price' => 115000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'VABIOTECH',
                'dosage' => '1.5ml',
                'category' => 'Tả',
                'is_featured' => false,
                'sort_order' => 32,
                'description' => 'Vắc xin đường uống phòng bệnh Tả.',
                'disease_prevention' => 'Bệnh Tả',
                'age_group' => '2 tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '32-morcvax.jfif',
            ],
            [
                'name' => 'Qdenga',
                'price' => 1250000,
                'sale_price' => 1250000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'Takeda',
                'dosage' => '0.5ml',
                'category' => 'Sốt xuất huyết',
                'is_featured' => true,
                'sort_order' => 33,
                'description' => 'Vắc xin phòng bệnh Sốt xuất huyết Dengue thế hệ mới giảm nguy cơ nhập viện lên đến 90%.',
                'disease_prevention' => 'Sốt xuất huyết Dengue',
                'age_group' => '4 tuổi trở lên',
                'origin' => 'Nhật Bản',
                'image' => '33-qdenga.jfif',
            ],
            [
                'name' => 'Gardasil 4',
                'price' => 1890000,
                'sale_price' => 1890000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'MSD',
                'dosage' => '0.5ml',
                'category' => 'HPV',
                'is_featured' => false,
                'sort_order' => 34,
                'description' => 'Vắc xin phòng 4 chủng HPV (6, 11, 16, 18) gây ung thư cổ tử cung và sùi mào gà.',
                'disease_prevention' => 'HPV – UTCTC',
                'age_group' => '9 đến 26 tuổi',
                'origin' => 'Mỹ',
                'image' => '34-garadasil-4.jpg',
            ],
            [
                'name' => 'Gardasil 9',
                'price' => 2950000,
                'sale_price' => 2950000,
                'type' => 'single',
                'doses' => 3,
                'stock_status' => 'available',
                'manufacturer' => 'MSD',
                'dosage' => '0.5ml',
                'category' => 'HPV',
                'is_featured' => true,
                'sort_order' => 35,
                'description' => 'Vắc xin phòng 9 chủng HPV bảo vệ toàn diện ung thư cổ tử cung và bệnh sinh dục ở nam và nữ.',
                'disease_prevention' => 'HPV – UTCTC (9 chủng)',
                'age_group' => '9 đến 45 tuổi',
                'origin' => 'Mỹ',
                'image' => '35-gardasil-9.jpg',
            ],
            [
                'name' => 'TT/VAT',
                'price' => 150000,
                'sale_price' => 150000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'IVAC',
                'dosage' => '0.5ml',
                'category' => 'Uốn ván',
                'is_featured' => false,
                'sort_order' => 36,
                'description' => 'Vắc xin uốn ván hấp phụ phòng bệnh uốn ván cho phụ nữ mang thai và người bị vết thương.',
                'disease_prevention' => 'Uốn ván hấp phụ',
                'age_group' => '2 tháng tuổi trở lên',
                'origin' => 'Việt Nam',
                'image' => '36-u-n-v-n-tt.jpg',
            ],
            [
                'name' => 'Boostrix',
                'price' => 750000,
                'sale_price' => 750000,
                'type' => 'single',
                'doses' => 1,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Bạch hầu - Ho gà - Uốn ván',
                'is_featured' => true,
                'sort_order' => 37,
                'description' => 'Vắc xin tiêm nhắc Bạch hầu – Ho gà – Uốn ván cho trẻ từ 4 tuổi và thanh thiếu niên, người lớn.',
                'disease_prevention' => 'Bạch hầu – Ho gà – Uốn ván',
                'age_group' => '4 tuổi trở lên',
                'origin' => 'Bỉ',
                'image' => '37-boostrix.jpg',
            ],
            [
                'name' => 'Abhayrab',
                'price' => 280000,
                'sale_price' => 280000,
                'type' => 'single',
                'doses' => 5,
                'stock_status' => 'available',
                'manufacturer' => 'Human Biologicals Institute',
                'dosage' => '0.5ml',
                'category' => 'Dại',
                'is_featured' => false,
                'sort_order' => 38,
                'description' => 'Vắc xin phòng bệnh Dại sau khi bị động vật cắn hoặc tiêm phòng chủ động.',
                'disease_prevention' => 'Vắc xin phòng Dại',
                'age_group' => 'Mọi lứa tuổi',
                'origin' => 'Ấn Độ',
                'image' => '38-abhayrab.jpg',
            ],
            [
                'name' => 'Indirab',
                'price' => 280000,
                'sale_price' => 280000,
                'type' => 'single',
                'doses' => 5,
                'stock_status' => 'available',
                'manufacturer' => 'Micropharm',
                'dosage' => '0.5ml',
                'category' => 'Dại',
                'is_featured' => false,
                'sort_order' => 39,
                'description' => 'Vắc xin phòng bệnh Dại tế bào Vero.',
                'disease_prevention' => 'Vắc xin phòng Dại',
                'age_group' => 'Mọi lứa tuổi',
                'origin' => 'Ấn Độ',
                'image' => '39-indirab.jpg',
            ],
            [
                'name' => 'Shingrix',
                'price' => 3890000,
                'sale_price' => 3890000,
                'type' => 'single',
                'doses' => 2,
                'stock_status' => 'available',
                'manufacturer' => 'GSK',
                'dosage' => '0.5ml',
                'category' => 'Zona thần kinh',
                'is_featured' => true,
                'sort_order' => 40,
                'description' => 'Vắc xin tái tổ hợp thế hệ mới phòng bệnh Zona thần kinh và biến chứng đau thần kinh sau Zona.',
                'disease_prevention' => 'Zona thần kinh',
                'age_group' => '50 tuổi trở lên',
                'origin' => 'Bỉ',
                'image' => '40-shingrix.jfif',
            ],
            [
                'name' => 'Gói Vắc Xin Người Cao Tuổi & Bệnh Nền',
                'price' => 5200000,
                'sale_price' => 5200000,
                'type' => 'package',
                'doses' => 4,
                'stock_status' => 'available',
                'manufacturer' => 'Medicare',
                'dosage' => 'Gói 4 liều',
                'category' => 'Gói Vắc Xin',
                'is_featured' => true,
                'sort_order' => 41,
                'description' => 'Gói vắc xin thiết yếu khuyến nghị cho người cao tuổi và người có bệnh nền để bảo vệ hệ thần kinh và hô hấp. Gồm Phế cầu và Zona thần kinh.',
                'disease_prevention' => 'Cúm mùa, Phế cầu khuẩn, Zona thần kinh',
                'age_group' => 'Người lớn từ 50 tuổi trở lên',
                'origin' => 'Mỹ/Bỉ',
                'image' => 'goi-nguoi-cao-tuoi.jpg',
            ],
            [
                'name' => 'Gói Vắc Xin Toàn Diện Cho Trẻ Em (0 - 2 tuổi)',
                'price' => 16500000,
                'sale_price' => 16500000,
                'type' => 'package',
                'doses' => 12,
                'stock_status' => 'available',
                'manufacturer' => 'Medicare',
                'dosage' => 'Gói 12 liều',
                'category' => 'Gói Vắc Xin',
                'is_featured' => true,
                'sort_order' => 42,
                'description' => 'Gói tiêm trọn gói bảo vệ bé yêu vững chắc trong 2 năm đầu đời. Cam kết giữ đầy đủ tất cả vắc xin (6in1, Rota, Phế cầu, Thủy đậu...) theo đúng phác đồ tiêm.',
                'disease_prevention' => 'Bạch hầu, ho gà, uốn ván, bại liệt, viêm gan B, Hib, phế cầu, tiêu chảy Rota, thủy đậu',
                'age_group' => 'Trẻ em dưới 2 tuổi',
                'origin' => 'Pháp/Bỉ',
                'image' => 'goi-tre-em.jpg',
            ],
            [
                'name' => 'Gói Vắc Xin Tiền Hôn Nhân & Sức Khỏe Sinh Sản',
                'price' => 4500000,
                'sale_price' => 4500000,
                'type' => 'package',
                'doses' => 6,
                'stock_status' => 'available',
                'manufacturer' => 'Medicare',
                'dosage' => 'Gói 6 liều',
                'category' => 'Gói Vắc Xin',
                'is_featured' => true,
                'sort_order' => 43,
                'description' => 'Gói vắc xin bảo vệ cặp đôi trước khi kết hôn và chuẩn bị mang thai. Gồm vắc xin ngừa HPV (sùi mào gà/ung thư CTC), viêm gan B, và sởi - quai bị - rubella.',
                'disease_prevention' => 'HPV (sùi mào gà, ung thư CTC), viêm gan B, sởi, quai bị, rubella',
                'age_group' => 'Nam và nữ từ 9 đến 26 tuổi',
                'origin' => 'Mỹ/Bỉ',
                'image' => 'goi-tien-hon-nhan.jpg',
            ],
        ];

        foreach ($vaccines as $data) {
            Vaccine::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
        }
    }
}
